### ISSUE TITLE
Why IOU is null

### ISSUE THREAD

**Issue by Jiangyaoyu** [tangjiapeng/SA-ConvONet#9]
你好，请问当我在运行 python train.py  configs/pointcloud_crop/room_grid64.yaml时，为什么每次验证时IOU指标都为0？

**Comment by tangjiapeng** [comment]
Hi, you can check your dataloader.

**Comment by Jiangyaoyu** [comment]
@tangjiapeng Thank you very much for your reply. I checked my dataloader,but I didn't check what's wrong. Could you be specific about that.The name of the dataset is  synthetic_room_dataset. Looking forward to your reply again!

**Comment by tangjiapeng** [comment]
Hi, did you meet this issue during pretraining or test-time optimization ?

**Comment by Jiangyaoyu** [comment]
> Hi, did you meet this issue during pretraining or test-time optimization ?

@tangjiapeng Hi,I meet this issue during running "python train.py configs/pointcloud_crop/room_grid64.yaml " on synthetic_room_dataset.

**Comment by tangjiapeng** [comment]
Hi, in our method, we directly the pretrained model from the conv_onet without re-training it.
